# Generated by Django 4.2.15 on 2024-08-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("p3_dash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YourDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column1", models.CharField(max_length=255)),
                ("column2", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
